import family from '@/assets/diwali-family.jpg';
import productsImage from '@/assets/diwali-products.jpg';
import categoriesImage from '@/assets/diwali-categories.jpg';
import sky from '@/assets/diwali-sky.jpg';

export const PHONE = '9840023543';
export const LOCATION = 'Virudhunagar, Tamil Nadu - 626005';
export const generalMessage = 'Hi AGS CRACKER, I would like to know more about your crackers and offers.';
export const whatsapp = (message = generalMessage) => `https://wa.me/91${PHONE}?text=${encodeURIComponent(message)}`;
export const mapUrl = 'https://www.google.com/maps/search/?api=1&query=Virudhunagar%2C+Tamil+Nadu+626005';

export const slides = [
  { title: 'Light Up Your Celebrations', subtitle: 'Quality Crackers | Best Prices | Festive Offers', cta: 'Shop Now', url: '/products', image: family },
  { title: 'Celebrate More, Save More!', subtitle: 'Special Diwali Offers at Budget-Friendly Prices', cta: 'View Offers', url: '/combo-offers', image: productsImage },
  { title: 'Something for Every Celebration', subtitle: 'Explore Our Wide Range of Crackers', cta: 'Explore Products', url: '/products', image: categoriesImage },
  { title: 'Your Celebration Starts Here', subtitle: 'AGS CRACKER – Bringing Joy to Your Celebrations', cta: 'Shop Now', url: '/products', image: sky },
] as const;

export const categories = ["One Sound Crackers", "Ground Chakkars", "Fancy Crackers", "Flower Pots", "Colour Fountains", "Atom Bombs", "Paper Bombs", "Sparklers", "Colour Matches", "Special Sparkler", "Bijili Crackers", "Rockets", "Twinkling Star", "Pencil Varieties", "Special Pencils", "Safety Garlands", "Single Sky Shot", "Special Sky Shot", "Kids Items", "Power King Fountains", "Kids Novelties", "Night Special", "Sky Shots", "Set Out (JIBRAND)", "Ayvan Brand Amazing Fountains", "Mini Multi Shots", "Bada Fountains", "Deluxe Crackers", "Garlands", "Special Kids Items", "Gift Boxes"];

export type Product = {
  slug: string;
  name: string;
  category: string;
  image: string;
  description: string;
  mrp?: number;
  price?: number;
  unit?: string;
  available?: boolean;
};

/**
 * AGS CRACKER catalogue
 * Prices below are transcribed from the supplied AGS CRACKER price list.
 * MRP = source-list MRP, price = "After 89% Discount Price".
 * Product images use the closest existing category visual in the project.
 * Replace individual image fields with product photos whenever they are supplied.
 */
export const products: Product[] = [
  { slug: '1-23-4-kuruvi', name: "23/4\" Kuruvi", category: "One Sound Crackers", image: '/images/products/webp/kuruvi.webp', description: "23/4\" Kuruvi from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 70, price: 9, unit: "1 Pkt", available: true },
  { slug: '2-3-lakshmi-lokler', name: "3\" Lakshmi/Lokler", category: "One Sound Crackers", image: '/images/products/webp/lakshmi.webp', description: "3\" Lakshmi/Lokler from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 130, price: 15, unit: "1 Pkt", available: true },
  { slug: '3-4-lakshmi-lion', name: "4\" Lakshmi/Lion", category: "One Sound Crackers", image: '/images/products/webp/lakshmi4.webp', description: "4\" Lakshmi/Lion from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 180, price: 20, unit: "1 Pkt", available: true },
  { slug: '4-4-spiderman-deluxe', name: "4\" Spiderman Deluxe", category: "One Sound Crackers", image: '/images/products/webp/goldlakshmi.webp', description: "4\" Spiderman Deluxe from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 450, price: 50, unit: "1 Pkt", available: true },
  { slug: '5-4-gold-lakshmi', name: "4\" Gold Lakshmi", category: "One Sound Crackers", image: '/images/products/webp/goldlakshmi.webp', description: "4\" Gold Lakshmi from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 300, price: 33, unit: "1 Pkt", available: true },
  { slug: '6-5-jallikattu-english-5-bahubali', name: "5\" Jallikattu (English) & 5\" Bahubali", category: "One Sound Crackers", image: '/images/products/webp/jalikattu.webp', description: "5\" Jallikattu (English) & 5\" Bahubali from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 500, price: 55, unit: "1 Pkt", available: true },
  { slug: '7-5-jallikattu-tamil', name: "5\" Jallikattu (Tamil)", category: "One Sound Crackers", image: '/images/products/webp/jalikattu1.webp', description: "5\" Jallikattu (Tamil) from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 600, price: 66, unit: "1 Pkt", available: true },
  { slug: '8-2-sound-crackers', name: "2 Sound Crackers", category: "One Sound Crackers", image: '/images/products/webp/2sound.webp', description: "2 Sound Crackers from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 300, price: 33, unit: "1 Pkt", available: true },
  { slug: '9-ground-chakkar-big-10pcs', name: "Ground Chakkar Big (10Pcs)", category: "Ground Chakkars", image:'/images/products/webp/ground.webp', description: "Ground Chakkar Big (10Pcs) from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 350, price: 39, unit: "1 Box", available: true },
  { slug: '10-ground-chakkar-big-25pcs', name: "Ground Chakkar Big (25Pcs)", category: "Ground Chakkars", image: '/images/products/webp/ground.webp', description: "Ground Chakkar Big (25Pcs) from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 700, price: 77, unit: "1 Box", available: true },
  { slug: '11-ground-chakkar-special', name: "Ground Chakkar Special", category: "Ground Chakkars", image: '/images/products/webp/ground.webp', description: "Ground Chakkar Special from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 750, price: 83, unit: "1 Box", available: true },
  { slug: '12-ground-chakkar-deluxe', name: "Ground Chakkar Deluxe", category: "Ground Chakkars", image: '/images/products/webp/ground2.webp', description: "Ground Chakkar Deluxe from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1200, price: 132, unit: "1 Box", available: true },
  { slug: '13-plastic-spinner-mix', name: "Plastic Spinner Mix", category: "Fancy Crackers", image: '/images/products/webp/plastic.webp', description: "Plastic Spinner Mix from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 700, price: 77, unit: "1 Box", available: true },
  { slug: '14-plastic-spinner-small', name: "Plastic Spinner Small", category: "Fancy Crackers", image: '/images/products/webp/plastic2.webp', description: "Plastic Spinner Small from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1400, price: 154, unit: "1 Box", available: true },
  { slug: '15-plastic-spinner-deluxe', name: "Plastic Spinner Deluxe", category: "Fancy Crackers", image: '/images/products/webp/plastic3.webp', description: "Plastic Spinner Deluxe from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1800, price: 198, unit: "1 Box", available: true },
  { slug: '16-disco-wheel', name: "Disco Wheel", category: "Fancy Crackers", image: '/images/products/webp/disco.webp', description: "Disco Wheel from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1000, price: 110, unit: "1 Box", available: true },
  { slug: '17-4-fancy-wheel', name: "4\" Fancy Wheel", category: "Fancy Crackers", image: '/images/products/webp/disco4.webp', description: "4\" Fancy Wheel from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1500, price: 165, unit: "1 Box", available: true },
  { slug: '18-wire-chakkar', name: "Wire Chakkar", category: "Ground Chakkars", image: '/images/products/webp/disco4.webp', description: "Wire Chakkar from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1400, price: 154, unit: "1 Box", available: true },
  { slug: '19-whistling-wheel', name: "Whistling Wheel", category: "Fancy Crackers", image: '/images/products/webp/wheel.webp', description: "Whistling Wheel from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1600, price: 176, unit: "1 Box", available: true },
  { slug: '20-flower-pots-big', name: "Flower Pots Big", category: "Flower Pots", image: '/images/products/webp/flower.webp', description: "Flower Pots Big from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 500, price: 55, unit: "1 Box", available: true },
  { slug: '21-flower-pots-special', name: "Flower Pots Special", category: "Flower Pots", image: '/images/products/webp/flower2.webp', description: "Flower Pots Special from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 500, price: 55, unit: "1 Box", available: true },
  { slug: '22-flower-pots-asoka', name: "Flower Pots Asoka", category: "Flower Pots", image: '/images/products/webp/flower3.webp', description: "Flower Pots Asoka from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 855, price: 94, unit: "1 Box", available: true },
  { slug: '23-colour-koti-10pcs', name: "Colour Koti (10Pcs)", category: "Colour Fountains", image: '/images/products/webp/flower4.webp', description: "Colour Koti (10Pcs) from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1800, price: 198, unit: "1 Box", available: true },
  { slug: '24-colour-koti-deluxe-5pcs', name: "Colour Koti Deluxe (5Pcs)", category: "Colour Fountains", image: '/images/products/webp/flower5.webp', description: "Colour Koti Deluxe (5Pcs) from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1600, price: 176, unit: "1 Box", available: true },
  { slug: '25-colour-koti-super-deluxe-10pcs', name: "Colour Koti Super Deluxe (10Pcs)", category: "Colour Fountains", image:'/images/products/webp/flower3.webp', description: "Colour Koti Super Deluxe (10Pcs) from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 5000, price: 550, unit: "1 Box", available: true },
  { slug: '26-2-colour-fountain', name: "2 Colour Fountain", category: "Colour Fountains", image: '/images/products/webp/flower6.webp', description: "2 Colour Fountain from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1700, price: 187, unit: "1 Box", available: true },
  { slug: '27-flower-pot-red-green', name: "Flower Pot Red & Green", category: "Flower Pots", image: '/images/products/webp/red.webp', description: "Flower Pot Red & Green from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1800, price: 198, unit: "1 Box", available: true },
  { slug: '28-colour-koti-red-green', name: "Colour Koti Red & Green", category: "Colour Fountains", image: '/images/products/webp/red.webp', description: "Colour Koti Red & Green from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 2800, price: 308, unit: "1 Box", available: true },
  { slug: '29-colour-koti-pink', name: "Colour Koti Pink", category: "Colour Fountains", image: '/images/products/webp/flower7.webp', description: "Colour Koti Pink from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 4000, price: 440, unit: "1 Box", available: true },
  { slug: '30-bullet-bomb', name: "Bullet Bomb", category: "Atom Bombs", image: '/images/products/webp/bullet.webp', description: "Bullet Bomb from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 200, price: 22, unit: "1 Box", available: true },
  { slug: '31-hydro-bomb', name: "Hydro Bomb", category: "Atom Bombs", image: '/images/products/webp/hydro.webp', description: "Hydro Bomb from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 700, price: 77, unit: "1 Box", available: true },
  { slug: '32-king-of-kings-bomb', name: "King of Kings Bomb", category: "Atom Bombs", image: '/images/products/webp/king.webp', description: "King of Kings Bomb from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 900, price: 99, unit: "1 Box", available: true },
  { slug: '33-classic-bomb', name: "Classic Bomb", category: "Atom Bombs", image: '/images/products/webp/classic.webp', description: "Classic Bomb from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1100, price: 121, unit: "1 Box", available: true },
  { slug: '34-neutron-bomb', name: "Neutron Bomb", category: "Atom Bombs", image: '/images/products/webp/neutron.webp', description: "Neutron Bomb from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 2800, price: 308, unit: "1 Box", available: true },
  { slug: '35-paper-bomb-1-4kg', name: "Paper Bomb 1/4kg", category: "Paper Bombs", image: '/images/products/webp/paper.webp', description: "Paper Bomb 1/4kg from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 450, price: 50, unit: "1 Box", available: true },
  { slug: '36-paper-bomb-1-2kg', name: "Paper Bomb 1/2kg", category: "Paper Bombs", image: '/images/products/webp/paper2.webp', description: "Paper Bomb 1/2kg from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1000, price: 110, unit: "1 Box", available: true },
  { slug: '37-paper-bomb-1kg', name: "Paper Bomb 1kg", category: "Paper Bombs", image: '/images/products/webp/paper3.webp', description: "Paper Bomb 1kg from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 2000, price: 220, unit: "1 Box", available: true },
  { slug: '38-avatar-1-10pcs', name: "Avatar 1 (10Pcs)", category: "Fancy Crackers", image:'/images/products/webp/avatar.webp', description: "Avatar 1 (10Pcs) from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 2500, price: 275, unit: "1 Box", available: true },
  { slug: '39-avatar-2-10pcs', name: "Avatar 2 (10Pcs)", category: "Fancy Crackers", image:'/images/products/webp/avatar2.webp', description: "Avatar 2 (10Pcs) from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 3500, price: 385, unit: "1 Box", available: true },
  { slug: '40-god-of-war', name: "God Of War", category: "Fancy Crackers", image: '/images/products/webp/godofwar.webp', description: "God Of War from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1200, price: 132, unit: "1 Box", available: true },
  { slug: '41-rider', name: "Rider", category: "Fancy Crackers", image: '/images/products/webp/rider.webp', description: "Rider from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 700, price: 77, unit: "1 Box", available: true },
  { slug: '42-10-cm-electric-sparkler', name: "10 cm Electric Sparkler", category: "Sparklers", image: '/images/products/webp/electric.webp', description: "10 cm Electric Sparkler from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 160, price: 18, unit: "1 Box", available: true },
  { slug: '43-10-cm-colour-sparkler', name: "10 cm Colour Sparkler", category: "Sparklers", image: '/images/products/webp/electric2.webp', description: "10 cm Colour Sparkler from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 180, price: 20, unit: "1 Box", available: true },
  { slug: '44-10-cm-green-sparkler', name: "10 cm Green Sparkler", category: "Sparklers", image: '/images/products/webp/electric3.webp', description: "10 cm Green Sparkler from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 180, price: 20, unit: "1 Box", available: true },
  { slug: '45-10-cm-red-sparkler', name: "10 cm Red Sparkler", category: "Sparklers", image: '/images/products/webp/electric4.webp', description: "10 cm Red Sparkler from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 180, price: 20, unit: "1 Box", available: true },
  { slug: '46-12-cm-electric-sparkler', name: "12 cm Electric Sparkler", category: "Sparklers", image: '/images/products/webp/electric5.webp', description: "12 cm Electric Sparkler from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 260, price: 29, unit: "1 Box", available: true },
  { slug: '47-12-cm-colour-sparkler', name: "12 cm Colour Sparkler", category: "Sparklers", image: '/images/products/webp/electric6.webp', description: "12 cm Colour Sparkler from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 280, price: 31, unit: "1 Box", available: true },
  { slug: '48-12-cm-green-sparkler', name: "12 cm Green Sparkler", category: "Sparklers", image: '/images/products/webp/electric7.webp', description: "12 cm Green Sparkler from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 280, price: 31, unit: "1 Box", available: true },
  { slug: '49-12-cm-red-sparkler', name: "12 cm Red Sparkler", category: "Sparklers", image: '/images/products/webp/electric8.webp', description: "12 cm Red Sparkler from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 300, price: 33, unit: "1 Box", available: true },
  { slug: '50-15-cm-electric-sparkler', name: "15 cm Electric Sparkler", category: "Sparklers", image: '/images/products/webp/electric9.webp', description: "15 cm Electric Sparkler from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 380, price: 42, unit: "1 Box", available: true },
  { slug: '51-15-cm-colour-sparkler', name: "15 cm Colour Sparkler", category: "Sparklers", image: '/images/products/webp/electric10.webp', description: "15 cm Colour Sparkler from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 400, price: 44, unit: "1 Box", available: true },
  { slug: '52-15-cm-green-sparkler', name: "15 cm Green Sparkler", category: "Sparklers", image: '/images/products/webp/electric11.webp', description: "15 cm Green Sparkler from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 400, price: 44, unit: "1 Box", available: true },
  { slug: '53-15-cm-red-sparkler', name: "15 cm Red Sparkler", category: "Sparklers", image: '/images/products/webp/electric12.webp', description: "15 cm Red Sparkler from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 420, price: 46, unit: "1 Box", available: true },
  { slug: '54-30-cm-electric-sparkler', name: "30 cm Electric Sparkler", category: "Sparklers", image:'/images/products/webp/electric13.webp', description: "30 cm Electric Sparkler from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 400, price: 44, unit: "1 Box", available: true },
  { slug: '55-30-cm-colour-sparkler', name: "30 cm Colour Sparkler", category: "Sparklers", image: '/images/products/webp/electric14.webp', description: "30 cm Colour Sparkler from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 420, price: 46, unit: "1 Box", available: true },
  { slug: '56-30-cm-green-sparkler', name: "30 cm Green Sparkler", category: "Sparklers", image: '/images/products/webp/electric15.webp', description: "30 cm Green Sparkler from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 420, price: 46, unit: "1 Box", available: true },
  { slug: '57-30-cm-red-sparkler', name: "30 cm Red Sparkler", category: "Sparklers", image: '/images/products/webp/electric16.webp', description: "30 cm Red Sparkler from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 450, price: 50, unit: "1 Box", available: true },
  { slug: '58-50-cm-electric-sparkler', name: "50 cm Electric Sparkler", category: "Sparklers", image: '/images/products/webp/electric17.webp', description: "50 cm Electric Sparkler from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1550, price: 171, unit: "1 Box", available: true },
  { slug: '59-50-cm-colour-sparkler', name: "50 cm Colour Sparkler", category: "Sparklers", image: '/images/products/webp/electric18.webp', description: "50 cm Colour Sparkler from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1850, price: 204, unit: "1 Box", available: true },
  { slug: '60-candy-pop', name: "Candy Pop", category: "Colour Matches", image: '/images/products/webp/pop.webp', description: "Candy Pop from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 2000, price: 220, unit: "1 Box", available: true },
  { slug: '61-twister', name: "Twister", category: "Colour Matches", image: '/images/products/webp/twistter.webp', description: "Twister from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1750, price: 193, unit: "1 Box", available: true },
  { slug: '62-rider', name: "Rider", category: "Colour Matches", image: '/images/products/webp/rider2.webp', description: "Rider from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1200, price: 132, unit: "1 Box", available: true },
  { slug: '63-dancing-umbrella-6-in-1', name: "Dancing Umbrella (6 in 1)", category: "Special Sparkler", image: '/images/products/webp/um.webp', description: "Dancing Umbrella (6 in 1) from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1700, price: 187, unit: "1 Box", available: true },
  { slug: '64-vadakampatti-bijili', name: "Vadakampatti Bijili", category: "Bijili Crackers", image: '/images/products/webp/bijili.webp', description: "Vadakampatti Bijili from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 400, price: 44, unit: "1 Pkt", available: true },
  { slug: '65-stripped-bijili-100pcs', name: "Stripped Bijili (100pcs)", category: "Bijili Crackers", image: '/images/products/webp/bijili2.webp', description: "Stripped Bijili (100pcs) from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 350, price: 39, unit: "1 Pkt", available: true },
  { slug: '66-rocket-bomb', name: "Rocket Bomb", category: "Rockets", image: '/images/products/webp/rocket.webp', description: "Rocket Bomb from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 600, price: 66, unit: "1 Box", available: true },
  { slug: '67-lunik-express-rocket', name: "Lunik Express Rocket", category: "Rockets", image: '/images/products/webp/rocket2.webp', description: "Lunik Express Rocket from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1000, price: 110, unit: "1 Box", available: true },
  { slug: '68-2-sound-rocket', name: "2 Sound Rocket", category: "Rockets", image: '/images/products/webp/rocket3.webp', description: "2 Sound Rocket from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1300, price: 143, unit: "1 Box", available: true },
  { slug: '69-whistling-rocket', name: "Whistling Rocket", category: "Rockets", image: '/images/products/webp/rocket4.webp', description: "Whistling Rocket from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1600, price: 176, unit: "1 Box", available: true },
  { slug: '70-colour-rocket', name: "Colour Rocket", category: "Rockets", image: '/images/products/webp/rocket5.webp', description: "Colour Rocket from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 2500, price: 275, unit: "1 Box", available: true },
  { slug: '71-colour-short-rocket', name: "Colour Short Rocket", category: "Rockets", image: '/images/products/webp/rocket5.webp', description: "Colour Short Rocket from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 3500, price: 385, unit: "1 Box", available: true },
  { slug: '72-1-2-twinkling-star', name: "1/2\" Twinkling Star", category: "Twinkling Star", image: '/images/products/webp/start.webp', description: "1/2\" Twinkling Star from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 250, price: 28, unit: "1 Box", available: true },
  { slug: '73-4-twinkling-star', name: "4\" Twinkling Star", category: "Twinkling Star", image: '/images/products/webp/start.webp', description: "4\" Twinkling Star from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 650, price: 72, unit: "1 Box", available: true },
  { slug: '74-7-pencils-10pcs', name: "7\" Pencils (10Pcs)", category: "Pencil Varieties", image: '/images/products/webp/pencil.webp', description: "7\" Pencils (10Pcs) from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 300, price: 33, unit: "1 Box", available: true },
  { slug: '75-mercury-torch-selfie-stick-3pcs', name: "Mercury Torch / Selfie Stick (3Pcs)", category: "Pencil Varieties", image: '/images/products/webp/selfie.webp', description: "Mercury Torch / Selfie Stick (3Pcs) from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 600, price: 66, unit: "1 Box", available: true },
  { slug: '76-kitty-kids-pencil', name: "Kitty Kids Pencil", category: "Special Pencils", image: '/images/products/webp/pencil.webp', description: "Kitty Kids Pencil from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 600, price: 66, unit: "1 Box", available: true },
  { slug: '77-kung-fu-children-wala', name: "Kung Fu Children Wala", category: "Safety Garlands", image:  '/images/products/webp/wala.webp', description: "Kung Fu Children Wala from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 500, price: 55, unit: "1 Box", available: true },
  { slug: '78-mini-magic-whip', name: "Mini Magic Whip", category: "Safety Garlands", image: '/images/products/webp/whip.webp', description: "Mini Magic Whip from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1250, price: 138, unit: "1 Box", available: true },
  { slug: '79-colour-magic-whip', name: "Colour Magic Whip", category: "Safety Garlands", image: '/images/products/webp/whip.webp', description: "Colour Magic Whip from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1800, price: 198, unit: "1 Box", available: true },
  { slug: '80-1-chotta-fancy', name: "1\" Chotta Fancy", category: "Single Sky Shot", image: '/images/products/webp/sky.webp', description: "1\" Chotta Fancy from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 450, price: 49, unit: "1 Box", available: true },
  { slug: '81-2-colour-fancy', name: "2\" Colour Fancy", category: "Single Sky Shot", image: '/images/products/webp/sky2.webp', description: "2\" Colour Fancy from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 800, price: 88, unit: "1 Box", available: true },
  { slug: '82-3-1-2-colour-fancy', name: "3 1/2 Colour Fancy", category: "Single Sky Shot", image: '/images/products/webp/sky3.webp', description: "3 1/2 Colour Fancy from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 3000, price: 330, unit: "1 Box", available: true },
  { slug: '83-3-1-2-colour-fancy-7-step', name: "3 1/2 Colour Fancy 7 Step", category: "Single Sky Shot", image: '/images/products/webp/sky4.webp', description: "3 1/2 Colour Fancy 7 Step from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 3500, price: 385, unit: "1 Box", available: true },
  { slug: '84-4-colour-fancy-2-ball', name: "4\" Colour Fancy (2 Ball)", category: "Single Sky Shot", image: '/images/products/webp/4fancy.webp', description: "4\" Colour Fancy (2 Ball) from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 4500, price: 495, unit: "1 Box", available: true },
  { slug: '85-2-fancy-3pcs', name: "2\" Fancy 3Pcs", category: "Single Sky Shot", image: '/images/products/webp/2fancy.webp', description: "2\" Fancy 3Pcs from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 2200, price: 242, unit: "1 Box", available: true },
  { slug: '86-2-fancy-3pcs-3-step', name: "2\" Fancy 3Pcs 3 Step", category: "Single Sky Shot", image: '/images/products/webp/2fancy.webp', description: "2\" Fancy 3Pcs 3 Step from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 3000, price: 330, unit: "1 Box", available: true },
  { slug: '87-4-colour-fancy', name: "4\" Colour Fancy", category: "Single Sky Shot", image: '/images/products/webp/4color.webp', description: "4\" Colour Fancy from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 4000, price: 440, unit: "1 Box", available: true },
  { slug: '88-avyan-pink', name: "Avyan Pink", category: "Special Sky Shot", image: '/images/products/webp/pink.webp', description: "Avyan Pink from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 2000, price: 220, unit: "1 Box", available: true },
  { slug: '89-avyan-blue-bird', name: "Avyan Blue Bird", category: "Special Sky Shot", image: '/images/products/webp/blue.webp', description: "Avyan Blue Bird from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 2500, price: 275, unit: "1 Box", available: true },
  { slug: '90-35-pipe-7-step', name: "35 Pipe 7 Step", category: "Special Sky Shot", image: '/images/products/webp/35pipe.webp', description: "35 Pipe 7 Step from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 3500, price: 385, unit: "1 Box", available: true },
  { slug: '91-35-pipe-nayagara-falls', name: "35 Pipe Nayagara Falls", category: "Special Sky Shot", image: '/images/products/webp/35pipe.webp', description: "35 Pipe Nayagara Falls from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 3500, price: 385, unit: "1 Box", available: true },
  { slug: '92-kitkat', name: "KitKat", category: "Kids Items", image: '/images/products/webp/kitkat.webp', description: "KitKat from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 250, price: 28, unit: "1 Box", available: true },
  { slug: '93-colour-chitput', name: "Colour ChitPut", category: "Kids Items", image: '/images/products/webp/chitput.webp', description: "Colour ChitPut from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 400, price: 44, unit: "1 Box", available: true },
  { slug: '94-serpent-big', name: "Serpent Big", category: "Kids Items", image: '/images/products/webp/big.webp', description: "Serpent Big from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 450, price: 50, unit: "1 Box", available: true },
  { slug: '95-anaconda', name: "Anaconda", category: "Kids Items", image: '/images/products/webp/anaconda.webp', description: "Anaconda from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 900, price: 99, unit: "1 Box", available: true },
  { slug: '96-roll-cap', name: "Roll Cap", category: "Kids Items", image: '/images/products/webp/rollcap.webp', description: "Roll Cap from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 600, price: 66, unit: "1 Box", available: true },
  {
  slug: "assorted-cartoon",
  name: "Assorted Cartoon",
  category: "Toy & Novelty",
  image: "/images/products/assorted-cartoon.webp",
  description: "Assorted Cartoon",
  mrp: 545.45,
  price: 60,
  unit: "Piece",
  available: true,
},
  { slug: '97-emerald', name: "Emerald", category: "Colour Fountains", image: '/images/products/webp/fountain.webp', description: "Emerald from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1000, price: 110, unit: "1 Box", available: true },
  { slug: '98-jasmine', name: "Jasmine", category: "Colour Fountains", image: '/images/products/webp/jasmine.webp', description: "Jasmine from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1600, price: 176, unit: "1 Box", available: true },
  { slug: '99-sunflower', name: "Sunflower", category: "Colour Fountains", image: '/images/products/webp/sunflower.webp', description: "Sunflower from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1600, price: 176, unit: "1 Box", available: true },
  { slug: '100-jack-jill', name: "Jack & Jill", category: "Colour Fountains", image: '/images/products/webp/jackandjill.webp', description: "Jack & Jill from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1600, price: 176, unit: "1 Box", available: true },
  { slug: '101-cherry-red', name: "Cherry Red", category: "Colour Fountains", image: '/images/products/webp/cherry.webp', description: "Cherry Red from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1600, price: 176, unit: "1 Box", available: true },
  { slug: '102-panchavarna', name: "Panchavarna", category: "Colour Fountains", image: '/images/products/webp/panch.webp', description: "Panchavarna from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1600, price: 176, unit: "1 Box", available: true },
  { slug: '103-colour-galaxy', name: "Colour Galaxy", category: "Colour Fountains", image: '/images/products/webp/galaxy.webp', description: "Colour Galaxy from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 2200, price: 242, unit: "1 Box", available: true },
  { slug: '104-tin-shower', name: "Tin Shower", category: "Power King Fountains", image:'/images/products/webp/tin.webp', description: "Tin Shower from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1000, price: 110, unit: "1 Box", available: true },
  { slug: '105-money-blast', name: "Money Blast", category: "Power King Fountains", image: '/images/products/webp/moneyblast.webp', description: "Money Blast from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1800, price: 198, unit: "1 Box", available: true },
  { slug: '106-gunblast', name: "Gunblast", category: "Power King Fountains", image: '/images/products/webp/gun.webp', description: "Gunblast from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1500, price: 165, unit: "1 Box", available: true },
  { slug: '107-mega-water-shower', name: "Mega Water Shower", category: "Power King Fountains", image: '/images/products/webp/water.webp', description: "Mega Water Shower from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1500, price: 165, unit: "1 Box", available: true },
  { slug: '108-colour-smoke-3pcs', name: "Colour Smoke (3Pcs)", category: "Power King Fountains", image: '/images/products/webp/smoke.webp', description: "Colour Smoke (3Pcs) from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1500, price: 165, unit: "1 Box", available: true },
  { slug: '109-photo-flash', name: "Photo Flash", category: "Kids Novelties", image: '/images/products/webp/photo.webp', description: "Photo Flash from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 500, price: 55, unit: "1 Box", available: true },
  { slug: '110-colour-butterfly', name: "Colour Butterfly", category: "Kids Novelties", image: '/images/products/webp/butterfly.webp', description: "Colour Butterfly from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1000, price: 110, unit: "1 Box", available: true },
  { slug: '111-drone', name: "Drone", category: "Kids Novelties", image: '/images/products/webp/drone.webp', description: "Drone from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1000, price: 110, unit: "1 Box", available: true },
  { slug: '112-helicopter', name: "Helicopter", category: "Kids Novelties", image: '/images/products/webp/helicopter.webp', description: "Helicopter from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1000, price: 110, unit: "1 Box", available: true },
  { slug: '113-bambaram', name: "Bambaram", category: "Kids Novelties", image: '/images/products/webp/bambaram.webp', description: "Bambaram from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1000, price: 110, unit: "1 Box", available: true },
  { slug: '114-mega-siren-3pcs', name: "Mega Siren (3Pcs)", category: "Night Special", image: '/images/products/webp/siren.webp', description: "Mega Siren (3Pcs) from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 2000, price: 220, unit: "1 Box", available: true },
  { slug: '115-peacock-5face', name: "Peacock (5Face)", category: "Night Special", image: '/images/products/webp/peacock.webp', description: "Peacock (5Face) from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1800, price: 198, unit: "1 Box", available: true },
  { slug: '116-peacock-3face', name: "Peacock (3Face)", category: "Night Special", image: '/images/products/webp/peacock3.webp', description: "Peacock (3Face) from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1600, price: 176, unit: "1 Box", available: true },
  { slug: '117-bada-peacock-5faces', name: "Bada Peacock (5Faces)", category: "Night Special", image: '/images/products/webp/peacock5.webp', description: "Bada Peacock (5Faces) from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 3500, price: 385, unit: "1 Box", available: true },
  { slug: '118-cone-fountain-2pcs', name: "Cone Fountain (2Pcs)", category: "Night Special", image: '/images/products/webp/cone.webp', description: "Cone Fountain (2Pcs) from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 2000, price: 220, unit: "1 Box", available: true },
  { slug: '119-7-shots-5pcs', name: "7 Shots (5Pcs)", category: "Sky Shots", image: '/images/products/webp/7shot.webp', description: "7 Shots (5Pcs) from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1000, price: 110, unit: "1 Box", available: true },
  { slug: '120-12-shot-crackling', name: "12 Shot Crackling", category: "Sky Shots", image: '/images/products/webp/12shot.webp', description: "12 Shot Crackling from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1000, price: 110, unit: "1 Box", available: true },
  { slug: '121-12-shot-with-colour', name: "12 Shot With Colour", category: "Sky Shots", image: '/images/products/webp/12shot.webp', description: "12 Shot With Colour from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1300, price: 143, unit: "1 Box", available: true },
  { slug: '122-15-shot-multi-colour', name: "15 Shot Multi Colour", category: "Sky Shots", image: '/images/products/webp/15shot.webp', description: "15 Shot Multi Colour from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 2500, price: 275, unit: "1 Box", available: true },
  { slug: '123-25-shot-crackling', name: "25 Shot Crackling", category: "Sky Shots", image: '/images/products/webp/25shot.webp', description: "25 Shot Crackling from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 2500, price: 275, unit: "1 Box", available: true },
  { slug: '124-30-shot-multi-colour', name: "30 Shot Multi Colour", category: "Sky Shots", image: '/images/products/webp/30shot.webp', description: "30 Shot Multi Colour from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 4000, price: 440, unit: "1 Box", available: true },
  { slug: '125-50-shot-crackling', name: "50 Shot Crackling", category: "Sky Shots", image: '/images/products/webp/50shot.webp', description: "50 Shot Crackling from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 3500, price: 385, unit: "1 Box", available: true },
  { slug: '126-60-shot-multi-colour', name: "60 Shot Multi Colour", category: "Sky Shots", image:  '/images/products/webp/60shot.webp', description: "60 Shot Multi Colour from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 8000, price: 880, unit: "1 Box", available: true },
  { slug: '127-120-shot-multi-colour', name: "120 Shot Multi Colour", category: "Sky Shots", image: '/images/products/webp/120shot.webp', description: "120 Shot Multi Colour from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 15000, price: 1650, unit: "1 Box", available: true },
  { slug: '128-240-shot-multi-colour', name: "240 Shot Multi Colour", category: "Sky Shots", image: '/images/products/webp/240shot.webp', description: "240 Shot Multi Colour from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 30000, price: 3300, unit: "1 Box", available: true },
  { slug: '129-2-20-set-out', name: "2\" 20 Set out", category: "Set Out (JIBRAND)", image: '/images/products/webp/2.webp', description: "2\" 20 Set out from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 20000, price: 2200, unit: "1 Box", available: true },
  { slug: '130-cocktail-spinner-red-green', name: "Cocktail Spinner (Red, Green)", category: "Ayvan Brand Amazing Fountains", image:'/images/products/webp/cocktail.webp', description: "Cocktail Spinner (Red, Green) from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 750, price: 85, unit: "1 Box", available: true },
  { slug: '131-ninja-chakkar-multiple-chakkar', name: "Ninja Chakkar (Multiple Chakkar)", category: "Ayvan Brand Amazing Fountains", image: '/images/products/webp/ninja.webp', description: "Ninja Chakkar (Multiple Chakkar) from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1600, price: 176, unit: "1 Box", available: true },
  { slug: '132-zodiac-chakkar-multiple-chakkar', name: "Zodiac Chakkar (Multiple Chakkar)", category: "Ayvan Brand Amazing Fountains", image: '/images/products/webp/zodiac.webp', description: "Zodiac Chakkar (Multiple Chakkar) from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 2200, price: 245, unit: "1 Box", available: true },
  { slug: '133-pogo-mixed-red-white-violet-gold-silver', name: "Pogo Mixed (Red, White, Violet, Gold, Silver)", category: "Ayvan Brand Amazing Fountains", image: '/images/products/webp/pogo.webp', description: "Pogo Mixed (Red, White, Violet, Gold, Silver) from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 900, price: 99, unit: "1 Box", available: true },
  { slug: '134-lemon-tree-amber-yellow-silver-purple', name: "Lemon Tree (Amber, Yellow, Silver, Purple)", category: "Ayvan Brand Amazing Fountains", image: '/images/products/webp/lemontree.webp', description: "Lemon Tree (Amber, Yellow, Silver, Purple) from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1500, price: 165, unit: "1 Box", available: true },
  { slug: '135-purple-dove', name: "Purple Dove", category: "Ayvan Brand Amazing Fountains", image: '/images/products/webp/dove.webp', description: "Purple Dove from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 750, price: 85, unit: "1 Box", available: true },
  { slug: '136-laser-strike', name: "Laser Strike", category: "Ayvan Brand Amazing Fountains", image: '/images/products/webp/laser.webp', description: "Laser Strike from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1500, price: 165, unit: "1 Box", available: true },
  { slug: '137-rio-wheel-pink-red', name: "Rio Wheel (Pink, Red)", category: "Ayvan Brand Amazing Fountains", image: '/images/products/webp/redwheel.webp', description: "Rio Wheel (Pink, Red) from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 2500, price: 275, unit: "1 Box", available: true },
  { slug: '138-hand-shooter-2026-special', name: "Hand Shooter 2026 Special", category: "Ayvan Brand Amazing Fountains", image: '/images/products/webp/shoot.webp', description: "Hand Shooter 2026 Special from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 5000, price: 550, unit: "1 Piece", available: true },
  { slug: '139-canon-ball', name: "Canon Ball", category: "Ayvan Brand Amazing Fountains", image: '/images/products/webp/canon.webp', description: "Canon Ball from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1700, price: 187, unit: "1 Box", available: true },
  { slug: '140-selfie-stick-green', name: "Selfie Stick Green", category: "Ayvan Brand Amazing Fountains", image: '/images/products/webp/selfie.webp', description: "Selfie Stick Green from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1000, price: 110, unit: "1 Box", available: true },
  { slug: '141-penta-5pcs-jagajal-colour', name: "Penta (5Pcs) Jagajal Colour", category: "Mini Multi Shots", image: '/images/products/webp/penta.webp', description: "Penta (5Pcs) Jagajal Colour from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1700, price: 187, unit: "1 Box", available: true },
  { slug: '142-7-shot-special-audi-q7', name: "7 Shot Special Audi Q7", category: "Mini Multi Shots", image: '/images/products/webp/7shot.webp', description: "7 Shot Special Audi Q7 from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1000, price: 110, unit: "1 Box", available: true },
  { slug: '143-fantasy-elephant-magizh', name: "Fantasy Elephant (Magizh)", category: "Bada Fountains", image: '/images/products/webp/elephant.webp', description: "Fantasy Elephant (Magizh) from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 2000, price: 220, unit: "1 Box", available: true },
  { slug: '144-fantasy-lion-magizh', name: "Fantasy Lion (Magizh)", category: "Bada Fountains", image: '/images/products/webp/lion.webp', description: "Fantasy Lion (Magizh) from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 2000, price: 220, unit: "1 Box", available: true },
  { slug: '145-cylinder-red-green', name: "Cylinder (Red & Green)", category: "Bada Fountains", image: '/images/products/webp/cylinder.webp', description: "Cylinder (Red & Green) from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 2500, price: 275, unit: "1 Pcs", available: true },
  { slug: '146-sword-magizh', name: "Sword (Magizh)", category: "Bada Fountains", image: '/images/products/webp/sword.webp', description: "Sword (Magizh) from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 2500, price: 275, unit: "1 Box", available: true },
  { slug: '147-gun-squad-magizh', name: "Gun Squad (Magizh)", category: "Bada Fountains", image: '/images/products/webp/gun.webp', description: "Gun Squad (Magizh) from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1500, price: 165, unit: "1 Box", available: true },
  { slug: '148-bat-ball', name: "Bat & Ball", category: "Bada Fountains", image: '/images/products/webp/bat.webp', description: "Bat & Ball from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1800, price: 198, unit: "1 Box", available: true },
  { slug: '149-hanuman-khatam-fountain', name: "Hanuman Khatam Fountain", category: "Bada Fountains", image: '/images/products/webp/hanuman.webp', description: "Hanuman Khatam Fountain from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 2000, price: 220, unit: "1 Box", available: true },
  { slug: '150-28-chorsa', name: "28 Chorsa", category: "Deluxe Crackers", image: '/images/products/webp/28.webp', description: "28 Chorsa from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 137, price: 15, unit: "1 Pkt", available: true },
  { slug: '151-28-giant', name: "28 Giant", category: "Deluxe Crackers", image: '/images/products/webp/28.webp', description: "28 Giant from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 200, price: 22, unit: "1 Pkt", available: true },
  { slug: '152-56-giant', name: "56 Giant", category: "Deluxe Crackers", image: '/images/products/webp/28.webp', description: "56 Giant from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 400, price: 44, unit: "1 Pkt", available: true },
  { slug: '153-50-deluxe', name: "50 Deluxe", category: "Deluxe Crackers", image: '/images/products/webp/50.webp', description: "50 Deluxe from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1200, price: 132, unit: "1 Pkt", available: true },
  { slug: '154-100-deluxe', name: "100 Deluxe", category: "Deluxe Crackers", image: '/images/products/webp/100.webp', description: "100 Deluxe from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 2000, price: 220, unit: "1 Pkt", available: true },
  { slug: '155-100-wala', name: "100 Wala", category: "Garlands", image: '/images/products/webp/100wala.webp', description: "100 Wala from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 400, price: 44, unit: "1 Box", available: true },
  { slug: '156-1k-short', name: "1K Short", category: "Garlands", image:'/images/products/webp/1kshot.webp', description: "1K Short from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1700, price: 187, unit: "1 Box", available: true },
  { slug: '157-2k-short', name: "2K Short", category: "Garlands", image: '/images/products/webp/2kshot.webp', description: "2K Short from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 3400, price: 374, unit: "1 Box", available: true },
  { slug: '158-5k-short', name: "5K Short", category: "Garlands", image: '/images/products/webp/5kshot.webp', description: "5K Short from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 8500, price: 935, unit: "1 Box", available: true },
  { slug: '159-10k-short', name: "10K Short", category: "Garlands", image: '/images/products/webp/10kshot.webp', description: "10K Short from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 17000, price: 1870, unit: "1 Box", available: true },
  { slug: '160-1k-special', name: "1K Special", category: "Garlands", image: '/images/products/webp/1k.webp', description: "1K Special from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 3400, price: 374, unit: "1 Box", available: true },
  { slug: '161-poppings', name: "Poppings", category: "Special Kids Items", image: '/images/products/webp/poppings.webp', description: "Poppings from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1500, price: 165, unit: "1 Box", available: true },
  { slug: '162-tweet', name: "Tweet", category: "Special Kids Items", image: '/images/products/webp/tweet.webp', description: "Tweet from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1500, price: 165, unit: "1 Box", available: true },
  { slug: '163-6000-sound', name: "6000 Sound", category: "Special Kids Items", image: '/images/products/webp/6000.webp', description: "6000 Sound from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1500, price: 165, unit: "1 Box", available: true },
  { slug: '164-money-bank-3pcs', name: "Money Bank (3Pcs)", category: "Special Kids Items", image: '/images/products/webp/money.webp', description: "Money Bank (3Pcs) from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1000, price: 110, unit: "1 Box", available: true },
  { slug: '165-money-bank-2pcs', name: "Money Bank (2Pcs)", category: "Special Kids Items", image: '/images/products/webp/money.webp', description: "Money Bank (2Pcs) from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1600, price: 176, unit: "1 Box", available: true },
  { slug: '166-mega-money-bank', name: "Mega Money Bank", category: "Special Kids Items", image: '/images/products/webp/money.webp', description: "Mega Money Bank from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1800, price: 198, unit: "1 Box", available: true },
  { slug: '167-old-is-gold', name: "Old Is Gold", category: "Special Kids Items", image: '/images/products/webp/specialitems.webp', description: "Old Is Gold from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 1200, price: 132, unit: "1 Box", available: true },
  {
  slug: "gun",
  name: "Gun",
  category: "Toy & Novelty",
  image: "/images/products/gun20.png",
  description: "Fun toy gun",
  mrp: 454.55,
  price: 50,
  unit: "Piece",
  available: true,
},

{
  slug: "ring",
  name: "Ring",
  category: "Novelty Items",
  image: "/images/products/ring.png",
  description: "Fun ring cracker",
  mrp: 72.73,
  price: 8,
  unit: "Piece",
  available: true,
},

{
  slug: "whistle-bullet",
  name: "Whistle Bullet",
  category: "Novelty Items",
  image: "/images/products/whistle.png",
  description: "Whistle bullet cracker",
  mrp: 1545.45,
  price: 170,
  unit: "Box",
  available: true,
},

{
  slug: "money-monkey-rain",
  name: "Money Monkey Rain",
  category: "Novelty Items",
  image: "/images/products/money-monkey-rain.png",
  description: "Money Monkey Rain cracker",
  mrp: 1800,
  price: 198,
  unit: "Box",
  available: true,
},

{
  slug: "touser-dinosaur",
  name: "Touser Dinosaur",
  category: "Novelty Items",
  image: "/images/products/dino.png",
  description: "Dinosaur themed cracker",
  mrp: 2545.45,
  price: 280,
  unit: "Box",
  available: true,
},

{
  slug: "gundu-malli",
  name: "Gundu Malli",
  category: "Novelty Items",
  image: "/images/products/gundu-malli.png",
  description: "Gundu Malli cracker",
  mrp: 1800,
  price: 198,
  unit: "Box",
  available: true,
},

{
  slug: "wife-tourser-singer",
  name: "Wife Tourser Singer",
  category: "Novelty Items",
  image: "/images/products/wife.png",
  description: "Wife Tourser Singer cracker",
  mrp: 1800,
  price: 198,
  unit: "Box",
  available: true,
},

{
  slug: "madurai-parotta",
  name: "Madurai Parotta",
  category: "Novelty Items",
  image: "/images/products/madurai.png",
  description: "Madurai Parotta cracker",
  mrp: 1800,
  price: 198,
  unit: "Box",
  available: true,
},

{
  slug: "mottu-samosa",
  name: "Mottu Samosa",
  category: "Novelty Items",
  image: "/images/products/motu.png",
  description: "Mottu Samosa cracker",
  mrp: 1800,
  price: 198,
  unit: "Box",
  available: true,
},

{
  slug: "mamiyar-missile-rocket",
  name: "Mamiyar Missile Rocket",
  category: "Rockets",
  image: "/images/products/mamiyar-missile-rocket.png",
  description: "Mamiyar Missile Rocket",
  mrp: 2181.82,
  price: 240,
  unit: "Box",
  available: true,
},
{
  slug: "top-gun-5pcs",
  name: "Top Gun (5Pcs)",
  category: "Toy & Novelty",
  image: "/images/products/top-gun-5pcs.webp",
  description: "Top Gun (5Pcs)",
  mrp: 1636.36,
  price: 180,
  unit: "Pack",
  available: true,
},

{
  slug: "small-military-gun",
  name: "Small Military Gun",
  category: "Toy & Novelty",
  image: "/images/products/small-military-gun.webp",
  description: "Small Military Gun",
  mrp: 1636.36,
  price: 180,
  unit: "Piece",
  available: true,
},

{
  slug: "shooting-gun-medium",
  name: "Shooting Gun Medium",
  category: "Toy & Novelty",
  image: "/images/products/shooting-gun-big.webp",
  description: "Shooting Gun Medium",
  mrp: 1727.27,
  price: 190,
  unit: "Piece",
  available: true,
},

{
  slug: "shooting-gun-big",
  name: "Shooting Gun Big",
  category: "Toy & Novelty",
  image: "/images/products/shooting-gun-medium.webp",
  description: "Shooting Gun Big",
  mrp: 1863.64,
  price: 205,
  unit: "Piece",
  available: true,
},
  { slug: '168-20-item-box', name: "20 Item Box", category: "Gift Boxes", image: '/images/products/webp/giftbox2.webp', description: "20 Item Box from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 3000, price: 330, unit: "1 Box", available: true },
  { slug: '169-25-item-box', name: "25 Item Box", category: "Gift Boxes", image: '/images/products/webp/giftbox2.webp', description: "25 Item Box from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 4000, price: 440, unit: "1 Box", available: true },
  { slug: '170-30-item-box', name: "30 Item Box", category: "Gift Boxes", image: '/images/products/webp/giftbox2.webp', description: "30 Item Box from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 4500, price: 495, unit: "1 Box", available: true },
  { slug: '171-40-item-box', name: "40 Item Box", category: "Gift Boxes", image: '/images/products/webp/giftbox2.webp', description: "40 Item Box from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 6900, price: 760, unit: "1 Box", available: true },
  { slug: '172-50-item-box', name: "50 Item Box", category: "Gift Boxes", image: '/images/products/webp/giftbox.webp', description: "50 Item Box from the AGS CRACKER festive collection. Listed price and unit are based on the supplied price list.", mrp: 9500, price: 1050, unit: "1 Box", available: true },
];

export const gallery = [
  { image: family, label: 'Festive family celebration', kind: 'Celebrations' },
  { image: productsImage, label: 'Festive fireworks selection', kind: 'Products' },
  { image: categoriesImage, label: 'Fireworks varieties', kind: 'Products' },
  { image: sky, label: 'Fireworks in the night sky', kind: 'Celebrations' },
] as const;

export function priceText(value?: number) {
  return value == null ? 'Price on request' : `₹${value.toLocaleString('en-IN')}`;
}

export function discount(product: Product) {
  return product.mrp && product.price && product.mrp > product.price
    ? Math.round((1 - product.price / product.mrp) * 100)
    : null;
}

