import { createFileRoute } from '@tanstack/react-router';
import { ArrowRight, Gift, MessageCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PageIntro } from '@/components/store/site';
import { slides, whatsapp } from '@/lib/catalogue';
export const Route = createFileRoute('/combo-offers')({ head: () => ({ meta: [{ title: 'Combo Offers | AGS CRACKER' }, { name: 'description', content: 'Ask AGS CRACKER about family, kids, premium, budget and festival fireworks combo offers in Virudhunagar.' }, { property: 'og:title', content: 'Combo Offers | AGS CRACKER' }, { property: 'og:description', content: 'Find a festive fireworks combo for your celebration. Enquire for current details.' }, { property: 'og:type', content: 'website' }, { name: 'twitter:card', content: 'summary_large_image' }] }), component: ComboOffers });
const combos = [
  { name: 'Family Combo', text: 'Something for everyone around the celebration.', image: slides[0].image },
  { name: 'Kids Combo', text: 'A festive selection to enquire about for family celebrations.', image: slides[2].image },
  { name: 'Premium Combo', text: 'Make the festive moments feel extra special.', image: slides[1].image },
  { name: 'Budget Combo', text: 'Ask us about options that fit your celebration.', image: slides[2].image },
  { name: 'Festival Combo', text: 'A selection for the big festival occasions.', image: slides[3].image },
];
function ComboOffers() { return <main><PageIntro eyebrow="Celebrate more" title="Combo Offers" description="Thoughtful assortments for celebrations of every size. Get in touch for the current contents and prices." /><section className="page-container section-space"><div className="grid gap-5 md:grid-cols-2">{combos.map((combo, i) => <article key={combo.name} className={`relative min-h-[330px] overflow-hidden rounded-sm bg-navy ${i === 0 ? 'md:col-span-2 md:min-h-[390px]' : ''}`}><img src={combo.image} alt={`${combo.name} festive fireworks illustration`} loading="lazy" className="absolute inset-0 h-full w-full object-cover transition-transform duration-500 hover:scale-105" /><div className="hero-shade absolute inset-0" /><div className="relative flex h-full max-w-md flex-col justify-end p-7 text-secondary-foreground sm:p-10"><Gift size={22} className="mb-3 text-gold" /><h2 className="display-title text-4xl sm:text-5xl">{combo.name}</h2><p className="mt-2 text-sm leading-6 text-secondary-foreground/80">{combo.text}</p><p className="mt-4 text-xs font-semibold uppercase tracking-wider text-gold">Details & price on request</p><div className="mt-5 flex flex-wrap gap-2"><Button asChild variant="gold" size="sm"><a href={whatsapp(`Hi AGS CRACKER, I would like to know more about the ${combo.name}. Please share the details.`)} target="_blank" rel="noopener noreferrer">View Combo <ArrowRight /></a></Button><Button asChild variant="light" size="sm"><a href={whatsapp(`Hi AGS CRACKER, I am interested in the ${combo.name}. Please share the contents and price.`)} target="_blank" rel="noopener noreferrer"><MessageCircle /> WhatsApp Enquiry</a></Button></div></div></article>)}</div><p className="mt-8 text-sm text-muted-foreground">Combo contents and pricing will be displayed when confirmed by AGS CRACKER.</p></section></main>; }
